//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computers()
        {
            this.DepartmentsAndComputers = new HashSet<DepartmentsAndComputers>();
        }
    
        public int id { get; set; }
        public int idMotherBoard { get; set; }
        public int idProcessor { get; set; }
        public int idRam { get; set; }
        public int RamPlatesCount { get; set; }
        public Nullable<int> idVideoAdapter { get; set; }
        public int idDriveSet { get; set; }
        public string Username { get; set; }
    
        public virtual DriveSets DriveSets { get; set; }
        public virtual Motherboards Motherboards { get; set; }
        public virtual Processors Processors { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual VideoAdapts VideoAdapts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentsAndComputers> DepartmentsAndComputers { get; set; }
    }
}
