//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentsAndComputers
    {
        public int id { get; set; }
        public int idComputer { get; set; }
        public int idDepartment { get; set; }
    
        public virtual Computers Computers { get; set; }
        public virtual Departments Departments { get; set; }
    }
}
