//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drives
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drives()
        {
            this.DriveSets = new HashSet<DriveSets>();
            this.DriveSets1 = new HashSet<DriveSets>();
        }
    
        public int id { get; set; }
        public int idType { get; set; }
        public int idManufacturer { get; set; }
        public int Volume { get; set; }
        public string Model { get; set; }
    
        public virtual DrivesTypes DrivesTypes { get; set; }
        public virtual HardwareManufacturers HardwareManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriveSets> DriveSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriveSets> DriveSets1 { get; set; }
    }
}
