//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processors()
        {
            this.Computers = new HashSet<Computers>();
        }
    
        public int id { get; set; }
        public int idModel { get; set; }
        public int idVendor { get; set; }
        public int idMark { get; set; }
        public int idSocket { get; set; }
        public Nullable<int> idIndex { get; set; }
        public int CacheL1 { get; set; }
        public int CacheL2 { get; set; }
        public Nullable<int> CacheL3 { get; set; }
        public string Tickspeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computers> Computers { get; set; }
        public virtual ProcessorsIndexes ProcessorsIndexes { get; set; }
        public virtual ProcessorsMarks ProcessorsMarks { get; set; }
        public virtual ProcessorsModels ProcessorsModels { get; set; }
        public virtual ProcessorsVendors ProcessorsVendors { get; set; }
        public virtual Sockets Sockets { get; set; }
    }
}
