//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessorsVendorsAndModels
    {
        public int id { get; set; }
        public int idVendor { get; set; }
        public int idModel { get; set; }
    
        public virtual ProcessorsModels ProcessorsModels { get; set; }
        public virtual ProcessorsVendors ProcessorsVendors { get; set; }
    }
}
