//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR.Res.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProcessorsStandart
    {
        public int id { get; set; }
        public int CacheL1 { get; set; }
        public int CacheL2 { get; set; }
        public Nullable<int> CacheL3 { get; set; }
        public string Tickspeed { get; set; }
        public string vName { get; set; }
        public string Picture { get; set; }
        public string Mark { get; set; }
        public string Name { get; set; }
        public string Socket { get; set; }
    }
}
