//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatPhoto
    {
        public int Id_Format { get; set; }
        public string Format { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
