//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoOneType
    {
        public int Id_PhotoOneType { get; set; }
        public Nullable<int> IdCount { get; set; }
        public Nullable<int> Id_Fromat { get; set; }
        public Nullable<int> Id_Type { get; set; }
    }
}
