//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quantity
    {
        public int Id_Q { get; set; }
        public Nullable<int> quantity1 { get; set; }
        public Nullable<int> price { get; set; }
    }
}
