//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TONAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public int Id_type { get; set; }
        public string type1 { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
